import {escape,money,timestamp,status} from './ui.js';
import {editExpense,deleteExpense} from './expense-mutation.js';
export function compareActivity(a,b){const delta=(Date.parse(b.row.created_at)||0)-(Date.parse(a.row.created_at)||0);return delta||`${a.kind}:${a.row.id}`.localeCompare(`${b.kind}:${b.row.id}`);}
export function createActivityFeed(fetchPage){
 const sources=['sales','expenses'].map(kind=>({kind,offset:0,buffer:[],done:false}));let running=null;
 async function next(){const snapshot=sources.map(s=>({...s,buffer:[...s.buffer]}));try{const result=[];while(result.length<20){const loads=await Promise.allSettled(sources.filter(s=>!s.done&&!s.buffer.length).map(async s=>{const rows=await fetchPage(s.kind,s.offset);s.offset+=rows.length;s.done=rows.length<20;s.buffer.push(...rows.map(row=>({kind:s.kind,row})));}));const failure=loads.find(x=>x.status==='rejected');if(failure)throw failure.reason;const heads=sources.filter(s=>s.buffer.length).sort((a,b)=>compareActivity(a.buffer[0],b.buffer[0]));if(!heads.length)break;result.push(heads[0].buffer.shift());}return result;}catch(e){sources.forEach((s,i)=>Object.assign(s,snapshot[i]));throw e;}}
 return {next(){if(!running)running=next().finally(()=>running=null);return running;},hasMore(){return sources.some(s=>!s.done||s.buffer.length);}};
}
function expenseDetails({item,api,projectId,mode,allowMutations,onSaved}){
 const dialog=document.createElement('dialog');dialog.innerHTML=`<h2>تفاصيل المصروف</h2><div class="panel row"><div><b>${escape(item.description)}</b><p>${['daily_wage','daily_wages'].includes(item.category)?'يوميات':'مصروف'}</p><small>${escape(timestamp(item.created_at))}</small></div><strong class="expense-amount">−${money(item.amount)}</strong></div><div class="panel row"><span>الدفع من</span><b>${escape(item.account?.name||'غير محدد')}</b></div><p class="muted small">إرفاق الفاتورة قيد الاستكمال.</p><div class="actions">${mode==='owner'&&allowMutations?'<button data-edit>تعديل</button><button data-delete class="danger">حذف</button>':''}<button data-close class="primary">إغلاق</button></div>`;document.body.append(dialog);dialog.showModal();dialog.querySelector('[data-close]').onclick=()=>dialog.remove();const options={api,projectId,item,mode,onSaved:()=>{dialog.remove();onSaved();}};dialog.querySelector('[data-edit]')?.addEventListener('click',()=>editExpense(options));dialog.querySelector('[data-delete]')?.addEventListener('click',()=>deleteExpense(options));
}
export async function renderActivity({api,projectId,container,isCurrent,mode,onSaved,allowMutations,onSale}){
 container.innerHTML='<h2>سجل العمليات</h2><label class="activity-search"><input type="search" data-search placeholder="بحث برقم العملية أو رقم جوال الزبون"><span aria-hidden="true">⌕</span></label><div data-records></div><p role="alert"></p><button data-more class="outline">تحميل المزيد</button>';
 const feed=createActivityFeed((kind,offset)=>api.rows(kind,projectId,kind==='sales'?'*,customer:sharikx2_customers(name,phone)':'*,account:sharikx2_accounts(name)',offset));let entries=[];
 function draw(){const q=container.querySelector('[data-search]').value;const visible=entries.filter(({row:x})=>`${x.description||''} ${x.customer?.name||''} ${x.customer?.phone||''} ${x.sale_number||''}`.includes(q));container.querySelector('[data-records]').innerHTML=visible.map(({kind,row:x},i)=>`<button class="panel row record activity-record" data-index="${i}"><div><b>${kind==='sales'?`مبيعة #${escape(x.sale_number)}`:escape(x.description)}</b><p>${escape(kind==='sales'?x.customer?.name||'زبون غير محدد':['daily_wage','daily_wages'].includes(x.category)?'يوميات':'مصروف')}</p><small>${escape(timestamp(x.created_at))}</small></div><div><strong class="${kind==='expenses'?'expense-amount':''}">${kind==='expenses'?'−':''}${money(kind==='sales'?x.total:x.amount)}</strong><span class="badge">${kind==='sales'?escape(status(x.status)):'مصروف'}</span></div></button>`).join('')||'<p class="muted">لا توجد نتائج</p>';container.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>{const entry=visible[Number(b.dataset.index)];if(entry.kind==='sales')onSale(entry.row.id);else expenseDetails({item:entry.row,api,projectId,mode,onSaved,allowMutations});});container.querySelector('[data-more]').hidden=!feed.hasMore();}
 async function more(){const b=container.querySelector('[data-more]');b.disabled=true;b.textContent='جارٍ التحميل…';try{const page=await feed.next();if(!isCurrent()||!container.isConnected)return;entries.push(...page);draw();}catch(e){container.querySelector('[role=alert]').textContent=e.message;}finally{b.disabled=false;b.textContent='تحميل المزيد';}}
 container.querySelector('[data-search]').oninput=draw;container.querySelector('[data-more]').onclick=more;await more();
}
