import {Api} from './api.js';
import {escape,money,timestamp,status,setCurrency} from './ui.js';
import {openExpense,renderExpenses} from './expense.js';
import {openSale} from './sale.js';
import {renderActivity} from './activity.js';
import {openTransfer} from './transfer.js';
import {openPurchase} from './purchase.js';
import {openPayment} from './payment.js';
import {openCollection} from './collection.js';
import {openReturn} from './return-ui.js';
import {canReturnSale,hasPendingReturn} from './return.js';
import {openOnboarding} from './onboarding.js';
import {icon} from './icons.js';
import {createReportState,renderReports} from './report-ui.js';
import {renderPartners} from './partners-ui.js';
import {renderFinancialAccounts} from './accounts-ui.js';
import {renderCurrencySettings} from './currency-ui.js';
import {themeController} from './theme-bootstrap.js';
import {renderThemeSettings} from './theme-ui.js';
import {renderInventory} from './inventory-ui.js';
import {normalizeDebtSnapshot,debtPartition,debtSearch,DEBT_SETTLED_THRESHOLD} from './debt-model.js';
import {openDebtDetails} from './debt-details-ui.js';
import {openSupplierEditor} from './supplier-mutation.js';
import {openCustomer} from './customer.js';
import {openCustomerEditor} from './customer-mutation.js';
let sessionStore=null;try{sessionStore=window.sessionStorage;}catch{}
const api=new Api(window.SHARIKX2_CONFIG,sessionStore),app=document.querySelector('#app');
let project=null,mode='owner',screen='cashier',epoch=0,accountPeriod='month';
let reportState=createReportState();
let installPrompt=null;
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;const button=document.createElement('button');button.className='outline';button.textContent='تثبيت التطبيق';button.onclick=async()=>{button.disabled=true;await installPrompt.prompt();installPrompt=null;button.remove();};document.querySelector('#notice')?.append(button);});
function notice(message){document.querySelector('#notice').textContent=message;}
function entry(){epoch++;project=null;setCurrency('ILS');reportState=createReportState();openOnboarding({app,api,onOpen:(opened,role)=>{project=opened;mode=role;setCurrency(project.currency);screen='cashier';shell();}});}
function shell(){
 const revision=++epoch;
 const navigation=[['accounts','الحسابات','accounts'],['products','البضاعة','inventory'],['cashier','الكاشير','cashier'],['partners','الشركاء','partners'],['reports','التقارير','reports']];
 app.innerHTML=`<div class="workspace"><header class="app-header"><div class="project-heading"><h1><span class="project-pencil">✎</span>${escape(project.name)}</h1><small>#${escape(project.project_number||'')}</small><div class="plan-line"><button data-plan class="plan-info">${mode==='viewer'?'مشاهدة فقط':project.subscription_status==='active'?'حساب مفعل':'خطة مجانية'} ⓘ</button>${mode==='owner'&&project.subscription_status!=='active'?'<button data-subscribe class="subscribe">اشترك الآن</button>':''}</div></div><div class="header-tools"><button data-menu aria-label="القائمة الجانبية">${icon('menu',26)}</button><button data-notifications aria-label="الإشعارات">${icon('bell',26)}</button></div></header><section id="content"></section><nav aria-label="التنقل الرئيسي">${navigation.map(([id,title,symbol])=>`<button data-page="${id}" class="${screen===id?'selected':''} ${id==='cashier'?'cashier-nav':''}" aria-current="${screen===id?'page':'false'}"><span class="nav-icon">${icon(symbol,id==='cashier'?27:24)}</span><span class="nav-label">${title}</span></button>`).join('')}</nav></div>`;
 app.querySelector('[data-menu]').onclick=()=>{const dialog=document.createElement('dialog');dialog.innerHTML=`<h2>القائمة</h2><div class="menu-list"><button data-go="settings">الإعدادات</button><button data-go="accounts">الحسابات</button><button data-go="cashier">الكاشير</button><button data-go="products">البضاعة</button><button data-go="partners">الشركاء</button><button data-go="reports">التقارير</button><button data-logout>تسجيل الخروج</button></div><button data-close class="outline">إغلاق</button>`;app.append(dialog);dialog.showModal();dialog.querySelector('[data-close]').onclick=()=>dialog.remove();dialog.querySelector('[data-logout]').onclick=()=>{api.clearSession();dialog.remove();entry();};dialog.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{screen=b.dataset.go;dialog.remove();shell();});};
 app.querySelector('[data-notifications]').onclick=()=>{const d=document.createElement('dialog');d.innerHTML='<h2>الإشعارات</h2><p class="muted">لا توجد إشعارات لعرضها حاليًا.</p><button class="primary">إغلاق</button>';app.append(d);d.showModal();d.querySelector('button').onclick=()=>d.remove();};
 app.querySelector('[data-plan]').onclick=()=>{const d=document.createElement('dialog');d.innerHTML=`<h2>حالة الحساب</h2><div class="panel">${mode==='viewer'?'المشروع متاح للمشاهدة فقط':project.subscription_status==='active'?'الاشتراك فعّال':'الخطة المجانية فعّالة'}</div><button class="primary">فهمت</button>`;app.append(d);d.showModal();d.querySelector('button').onclick=()=>d.remove();};
 app.querySelector('[data-subscribe]')?.addEventListener('click',()=>{screen='plans';shell();});
 app.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{screen=b.dataset.page;shell();});
 const content=app.querySelector('#content');content.innerHTML='<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>';load(content,revision);
}
async function load(content,revision){try{
 if(screen==='settings'){
  content.innerHTML='<h2>الإعدادات</h2>';
  renderThemeSettings({container:content,controller:themeController,isCurrent:()=>revision===epoch});
  renderCurrencySettings({api,container:content,project,mode,isCurrent:()=>revision===epoch,onSaved:shell});
 }else if(screen==='accounts'){
  await renderFinancialAccounts({api,project,container:content,isCurrent:()=>revision===epoch,periodMode:accountPeriod,onPeriodChange:value=>{accountPeriod=value;shell();}});
  if(revision!==epoch)return;
  renderCurrencySettings({api,container:content,project,mode,isCurrent:()=>revision===epoch,onSaved:shell});
  if(mode==='owner'&&window.SHARIKX2_CONFIG.transfers===true){const b=document.createElement('button');b.className='outline';b.textContent='التحويل بين الحسابات';content.append(b);b.onclick=()=>openTransfer({api,projectId:project.id,mode,storage:sessionStore,onSaved:shell});}
 }else if(['customers','suppliers'].includes(screen)){
  const data=await api.debts(project.id);if(revision!==epoch)return;
  const kind=screen,normalized=normalizeDebtSnapshot(data,kind),rows=normalized.rows;let archived=false,count=20;
  content.innerHTML=`<h2>${kind==='customers'?'ديون الزبائن':'ديون الموردين'}</h2><div class="actions">${mode==='owner'?(kind==='customers'?'<button class="primary" data-add-customer>إضافة زبون</button>':'<button class="primary" data-new-purchase>تسجيل فاتورة شراء</button>'):''}</div><div class="tabs"><button class="primary" data-tab="active">ديون عالقة</button><button data-tab="archive">أرشيف السداد</button></div><label class="search">بحث<input id="search" type="search" placeholder="الاسم أو رقم الجوال"></label><div class="panel metrics" data-debt-summary><span>إجمالي الديون العالقة<br><b>${money(normalized.total)}</b></span><span>عدد المدينين<br><b>${debtPartition(rows).length}</b></span></div><div id="rows"></div><button id="more" class="outline">تحميل المزيد</button>`;
  content.querySelector('[data-add-customer]')?.addEventListener('click',()=>openCustomer({api,projectId:project.id,mode,storage:sessionStore,isCurrent:()=>revision===epoch,onSaved:shell}));
  content.querySelector('[data-new-purchase]')?.addEventListener('click',()=>openPurchase({api,projectId:project.id,mode,storage:sessionStore,isCurrent:()=>revision===epoch,onSaved:shell}));
  const draw=()=>{const filtered=debtSearch(debtPartition(rows,archived),content.querySelector('#search').value);content.querySelector('[data-debt-summary]').hidden=archived;content.querySelector('#rows').innerHTML=filtered.slice(0,count).map(x=>`<article class="panel row" data-person="${escape(x.id)}"><div><button type="button" class="record-person" data-open-person="${escape(x.id)}">${escape(x.name)}</button><p class="muted">${escape(x.phone||'بدون رقم جوال')}</p>${mode==='owner'&&!archived?`<div class="actions">${kind==='customers'?`<button type="button" data-edit-customer="${escape(x.id)}">تعديل</button>`:`<button type="button" data-edit-supplier="${escape(x.id)}">تعديل</button><button type="button" data-archive-supplier="${escape(x.id)}">أرشفة</button>`}</div>`:''}${mode==='owner'&&Number(x.calculated_debt)>DEBT_SETTLED_THRESHOLD?`<button type="button" data-collect="${escape(x.id)}">${kind==='customers'?'تحصيل دفعة':'تسديد دفعة'}</button>`:`<small class="muted">اضغط على الاسم لعرض السجل</small>`}</div><strong>${money(archived?0:x.calculated_debt)}</strong></article>`).join('')||'<div class="panel">لا توجد نتائج</div>';content.querySelector('#more').hidden=filtered.length<=count;content.querySelectorAll('[data-edit-customer]').forEach(b=>b.onclick=e=>{e.stopPropagation();openCustomerEditor({api,projectId:project.id,customer:rows.find(x=>x.id===b.dataset.editCustomer),onSaved:shell});});content.querySelectorAll('[data-edit-supplier]').forEach(b=>b.onclick=e=>{e.stopPropagation();openSupplierEditor({api,projectId:project.id,supplier:rows.find(x=>x.id===b.dataset.editSupplier),onSaved:shell});});content.querySelectorAll('[data-archive-supplier]').forEach(b=>b.onclick=async e=>{e.stopPropagation();if(!window.confirm('هل تريد أرشفة المورد؟'))return;try{await api.archiveSupplier(project.id,b.dataset.archiveSupplier);shell();}catch(error){const alert=document.createElement('p');alert.setAttribute('role','alert');alert.textContent=error.message;content.prepend(alert);}});content.querySelectorAll('[data-collect]').forEach(b=>b.onclick=e=>{e.stopPropagation();const person=rows.find(x=>x.id===b.dataset.collect);personPayment(kind,person,revision);});content.querySelectorAll('[data-open-person]').forEach(b=>b.onclick=e=>{e.stopPropagation();personDetails(kind,rows.find(x=>x.id===b.dataset.openPerson));});content.querySelectorAll('[data-person]').forEach(b=>b.onclick=e=>{if(e.target.closest('button'))return;personDetails(kind,rows.find(x=>x.id===b.dataset.person));});};
  content.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{archived=b.dataset.tab==='archive';count=20;content.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('primary',x===b));draw();});content.querySelector('#search').oninput=()=>{count=20;draw();};content.querySelector('#more').onclick=()=>{count+=20;draw();};draw();
 }else if(screen==='cashier'){
  content.innerHTML=`<section class="cashier-intro"><h2>الكاشير</h2><p class="muted">سجّل المبيعات والديون والمصروفات من مكان واحد</p></section><div class="cashier-grid"><button data-sale><span class="action-icon"><img src="./assets/icon_cashier_colorful.png" alt=""></span><b>مبيعة جديدة</b></button><button data-customers><span class="action-icon"><img src="./assets/icon_customer_debt_colorful.png" alt=""></span><b>ديون الزبائن</b></button><button data-suppliers><span class="action-icon"><img src="./assets/icon_supplier_debt_colorful.png" alt=""></span><b>ديون الموردين</b></button><button data-expense><span class="action-icon"><img src="./assets/icon_expense_colorful.png" alt=""></span><b>مصروف جديد</b></button></div><button class="purchase-action" data-purchase><img src="./assets/icon_purchase_colorful.png" alt=""><span>تسجيل فاتورة شراء</span></button><section data-activity></section>`;
  content.querySelector('[data-customers]').onclick=()=>{screen='customers';shell();};content.querySelector('[data-suppliers]').onclick=()=>{screen='suppliers';shell();};
  if(mode==='owner'){content.querySelector('[data-sale]').onclick=()=>openSale({api,projectId:project.id,mode,storage:sessionStore,isCurrent:()=>revision===epoch,onSaved:shell});content.querySelector('[data-expense]').onclick=()=>openExpense({api,projectId:project.id,mode,container:app,storage:sessionStore,onSaved:shell});content.querySelector('[data-purchase]').onclick=()=>openPurchase({api,projectId:project.id,mode,storage:sessionStore,isCurrent:()=>revision===epoch,onSaved:shell});}else{content.querySelectorAll('[data-sale],[data-expense],[data-purchase]').forEach(b=>{b.disabled=true;b.title='المشروع للمشاهدة فقط';});}
  await renderActivity({api,projectId:project.id,container:content.querySelector('[data-activity]'),isCurrent:()=>revision===epoch,mode,onSaved:shell,allowMutations:window.SHARIKX2_CONFIG.expenseMutations===true,onSale:saleDetails});
 }else if(screen==='plans'){
  const features=[['حفظ المعلومات والحسابات','دائم','دائم'],['عدد الشركاء','2','غير محدود'],['المبيعات اليومية','100','غير محدود'],['أصناف البضاعة','25','غير محدود'],['عدد الموردين','5','غير محدود'],['تقارير شاملة','غير متاح','متاح'],['مشاركة المشروع','غير متاح','غير محدود']];
  content.innerHTML=`<section class="plans-screen"><h2>أهلًا وسهلًا بك</h2><p class="muted">استمتع باستخدام كامل المزايا بالنسخة المدفوعة</p><div class="plans-table"><div class="plan-head"><b>وجه المقارنة</b><b>المجاني</b><b>المدفوع ♛</b></div>${features.map(([title,free,paid])=>`<div class="plan-row"><span>${escape(title)}</span><span>${escape(free)}</span><span>${escape(paid)}</span></div>`).join('')}</div><div class="panel plan-price"><small>سعر الاشتراك الشهري</small><strong>30 ₪</strong><p class="muted">جميع المزايا الكاملة بدون قيود</p></div></section>`;
 }else if(screen==='reports'){
  await renderReports({api,project,container:content,state:reportState,isCurrent:()=>revision===epoch,onAccounts:()=>{screen='accounts';shell();},onPlans:()=>{screen='plans';shell();}});
 }else if(screen==='partners'){
  await renderPartners({api,projectId:project.id,container:content,mode,isCurrent:()=>revision===epoch,onSaved:shell});
 }else if(screen==='products'){
  await renderInventory({api,projectId:project.id,container:content,isCurrent:()=>revision===epoch,mode,onSaved:shell});
 }else{
  const table=screen==='cashier'?'sales':'products';const select=table==='sales'?'*,customer:sharikx2_customers(name,phone)':'*';let rows=await api.rows(table,project.id,select,0,table==='products'?{active:'eq.true'}:{});if(revision!==epoch)return;let offset=rows.length,hasMore=rows.length===20;
  content.innerHTML=`<h2>${table==='sales'?'سجل المبيعات':'البضاعة'}</h2><p class="muted small">عرض للقراءة فقط — عمليات الإضافة والتعديل قيد التنفيذ.</p><label>بحث في السجلات المحملة<input id="search" type="search" placeholder="ابحث بالاسم أو الرقم"></label><div id="rows"></div><p id="list-error" role="alert"></p><button id="more" class="outline">تحميل المزيد</button>`;
  if(table==='sales'){renderExpenses({api,projectId:project.id,container:content,isCurrent:()=>revision===epoch,mode,onSaved:shell,allowMutations:window.SHARIKX2_CONFIG.expenseMutations===true});if(mode==='owner'){const actions=document.createElement('div');actions.className='actions';actions.innerHTML='<button class="primary" data-new-sale>مبيعة جديدة</button><button data-new-expense>مصروف جديد</button>';content.prepend(actions);actions.querySelector('[data-new-sale]').onclick=()=>openSale({api,projectId:project.id,mode,storage:sessionStore,isCurrent:()=>revision===epoch,onSaved:()=>{notice('تم اعتماد المبيعة وإضافة المبلغ للحساب');shell();}});actions.querySelector('[data-new-expense]').onclick=()=>openExpense({api,projectId:project.id,mode,container:app,onSaved:()=>{notice('تم تسجيل المصروف وخصمه من الحساب');shell();},storage:sessionStore});}}
  const draw=()=>{const q=content.querySelector('#search').value;const shown=rows.filter(x=>`${x.name||''} ${x.customer?.name||''} ${x.sale_number||''}`.includes(q));content.querySelector('#rows').innerHTML=shown.map(x=>table==='sales'?`<button class="panel row record" data-sale="${escape(x.id)}"><div><b>مبيعة #${escape(x.sale_number)}</b><p>${escape(x.customer?.name||'زبون غير محدد')}</p><p class="muted">${escape(x.customer?.phone||'بدون رقم جوال')}</p><small>${escape(timestamp(x.created_at))}</small></div><div><strong>${money(x.total)}</strong><span class="badge">${escape(status(x.status))}</span></div></button>`:`<article class="panel"><p class="eyebrow">${escape(x.category||'بدون تصنيف')}</p><h2>${escape(x.name)}</h2><div class="metrics"><span>الوحدة<br><b>${escape(x.unit||'قطعة')}</b></span><span>سعر البيع<br><b>${money(x.sale_price,2)}</b></span></div><p class="muted">${escape(x.notes||'')}</p></article>`).join('')||'<div class="panel">لا توجد نتائج</div>';content.querySelector('#more').hidden=!hasMore;content.querySelectorAll('[data-sale]').forEach(b=>b.onclick=()=>saleDetails(b.dataset.sale));};
  content.querySelector('#search').oninput=draw;content.querySelector('#more').onclick=async e=>{const b=e.target;b.disabled=true;b.textContent='جارٍ التحميل…';try{const next=await api.rows(table,project.id,select,offset,table==='products'?{active:'eq.true'}:{});if(revision!==epoch)return;rows.push(...next);offset+=next.length;hasMore=next.length===20;draw();}catch(error){content.querySelector('#list-error').textContent=error.message;}finally{b.disabled=false;b.textContent='تحميل المزيد';}};draw();
 }
}catch(error){if(revision!==epoch)return;content.innerHTML='<div class="panel"><p role="alert"></p><button class="outline">إعادة المحاولة</button></div>';content.querySelector('p').textContent=error.message;content.querySelector('button').onclick=shell;}}
async function saleDetails(id){const dialog=document.createElement('dialog');dialog.innerHTML='<h2>تفاصيل المبيعة</h2><div class="details"><div class="skeleton"></div></div><div class="actions"><button data-return hidden disabled>إرجاع مبيعة</button><button class="primary">إغلاق</button></div>';app.append(dialog);dialog.showModal();dialog.querySelector('.primary').onclick=()=>dialog.remove();const revision=epoch;try{const s=await api.sale(project.id,id);if(!dialog.isConnected||revision!==epoch)return;if(!s)throw new Error('المبيعة غير موجودة');const returnButton=dialog.querySelector('[data-return]');returnButton.hidden=mode!=='owner'||(!hasPendingReturn(sessionStore,project.id,s.id)&&!canReturnSale(s));returnButton.disabled=returnButton.hidden;returnButton.onclick=()=>openReturn({api,projectId:project.id,mode,sale:s,storage:sessionStore,isCurrent:()=>revision===epoch,onSaved:()=>{dialog.remove();shell();}});dialog.querySelector('.details').innerHTML=`<div class="panel row"><div><b>${escape(s.customer?.name||'زبون غير محدد')}</b><p>${escape(s.customer?.phone||'بدون رقم جوال')}</p><small>${escape(timestamp(s.created_at))}</small></div><div><small>إجمالي المبيعة الحالي</small><h2>${money(s.total)}</h2></div></div><p>${escape(status(s.status))} · الاستلام: ${escape(s.payment_account?.name||'دين')}</p><h2>أصناف المبيعة</h2>${(s.items||[]).map(x=>`<div class="panel row"><div><b>${escape(x.product_name||x.name||'صنف')}</b><p class="muted">الكمية ${escape(x.quantity_pieces)} × ${money(x.unit_price,2)}</p></div><b>${money(x.line_total)}</b></div>`).join('')} ${(s.returns||[]).map(r=>`<div class="panel"><h2>مرتجع بقيمة ${money(r.total)}</h2><small>${escape(timestamp(r.created_at))}</small>${(r.items||[]).map(x=>`<p>كمية المرتجع: ${escape(x.quantity_pieces)} · ${money(x.refund_amount)}</p>`).join('')}</div>`).join('')}`;}catch(error){if(dialog.isConnected)dialog.querySelector('.details').textContent=error.message;}}
function personPayment(kind,person,revision=epoch,projectId=project.id){
 if(revision!==epoch)return;
 const options={api,projectId,mode,storage:sessionStore,isCurrent:()=>revision===epoch,onSaved:shell};
 return kind==='customers'?openCollection({...options,customer:person}):openPayment({...options,supplier:person});
}
function personDetails(kind,person){const revision=epoch,projectId=project.id;return openDebtDetails({api,container:app,projectId,kind,person,mode,storage:sessionStore,isCurrent:()=>revision===epoch,onSaved:shell,onDebtSale:customer=>openSale({api,projectId,mode,storage:sessionStore,initialCustomer:customer,isCurrent:()=>revision===epoch,onSaved:shell}),onCollect:person=>personPayment(kind,person,revision,projectId)});}
document.addEventListener('click',event=>{if(event.target.closest?.('#logout'))api.clearSession();},true);
entry();
if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js').then(reg=>{reg.addEventListener('updatefound',()=>{const worker=reg.installing;if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){const button=document.createElement('button');button.className='primary';button.textContent='تحديث التطبيق الآن';button.onclick=()=>{worker.postMessage({type:'SKIP_WAITING'});location.reload();};document.querySelector('#notice')?.append(button);}});});}).catch(()=>notice('تعذر تهيئة التثبيت؛ يمكنك الاستمرار باستخدام المتصفح'));
