import {escape,money} from './ui.js';import {createOperation} from './operations.js';
export function purchaseTotal(items){return items.reduce((n,x)=>n+Number(x.quantity)*Number(x.cost),0);}
export function purchasePayload(projectId,supplierId,items,payments,note=''){
 if(!supplierId||!items.length)throw new Error('اختر المورد وأضف صنفًا واحدًا على الأقل');
 if(items.some(x=>!Number.isFinite(x.quantity)||x.quantity<=0||!Number.isFinite(x.cost)||x.cost<0))throw new Error('تحقق من كمية وتكلفة الأصناف');
 if(payments.some(x=>!Number.isFinite(x.amount)||x.amount<=0)||new Set(payments.map(x=>x.account_id)).size!==payments.length)throw new Error('تحقق من دفعات الحسابات');
 return {p_project_id:projectId,p_supplier_id:supplierId,p_items:items.map(x=>({product_id:x.product_id,quantity_pieces:x.quantity,unit_cost:x.cost})),p_payments:payments.map(x=>({account_id:x.account_id,amount:x.amount})),p_invoice_number:null,p_note:note||null};
}
export async function openPurchase({api,projectId,mode,storage,onSaved}){
 if(mode!=='owner')throw new Error('المشاركة للمشاهدة فقط');if(document.querySelector('.purchase-dialog'))return;
 const d=document.createElement('dialog');d.className='purchase-dialog';d.innerHTML='<h2>فاتورة شراء جديدة</h2><div class="body"><div class="skeleton"></div></div><button data-close class="outline">إلغاء</button>';document.body.append(d);d.showModal();let busy=false,op=null,products=[],suppliers=[],accounts=[],items=[],payments=[];const key=`sharikx2-pending-purchase:${projectId}`;d.querySelector('[data-close]').onclick=()=>{if(!busy)d.remove();};d.oncancel=e=>{if(busy)e.preventDefault();};
 try{const [ps,ss,summary]=await Promise.all([api.rows('products',projectId,'*',0,{active:'eq.true'}),api.rows('suppliers',projectId,'*',0,{active:'eq.true'}),api.summary(projectId)]);if(!d.isConnected)return;products=ps;suppliers=ss;accounts=summary.accounts||[];d.querySelector('.body').innerHTML=`<form><fieldset><label>المورد<select name="supplier" required><option value="">اختر المورد</option>${suppliers.map(x=>`<option value="${escape(x.id)}">${escape(x.name)} — ${escape(x.phone||'بدون رقم')}</option>`).join('')}</select></label><h3>الأصناف</h3><div data-items></div><button type="button" class="outline" data-add>إضافة صنف</button><h3>الدفعات الحالية للمورد</h3><div data-payments></div><button type="button" class="outline" data-pay>إضافة دفعة</button><label>ملاحظات اختيارية<textarea name="note" maxlength="500"></textarea></label><div class="panel row"><span>الإجمالي</span><b data-total>0 ₪</b></div><div class="panel row"><span>المتبقي كدين للمورد</span><b data-debt>0 ₪</b></div></fieldset><p role="alert"></p><button class="primary" type="submit">تأكيد الفاتورة</button></form>`;const f=d.querySelector('form'),fs=f.querySelector('fieldset'),err=f.querySelector('[role=alert]'),submit=f.querySelector('[type=submit]');
 const draw=()=>{f.querySelector('[data-items]').innerHTML=items.map((x,i)=>`<div class="panel"><label>الصنف<select data-product="${i}">${products.map(p=>`<option value="${escape(p.id)}" ${p.id===x.product_id?'selected':''}>${escape(p.name)}</option>`).join('')}</select></label><div class="input-pair"><label>الكمية<input data-qty="${i}" type="number" min="0.001" step="0.001" value="${x.quantity}"></label><label>تكلفة الوحدة<input data-cost="${i}" type="number" min="0" step="0.01" value="${x.cost}"></label></div><button type="button" data-remove="${i}" class="danger">حذف الصنف</button></div>`).join('')||'<p class="muted">لم تُضف أصنافًا بعد</p>';f.querySelector('[data-payments]').innerHTML=payments.map((x,i)=>`<div class="panel"><label>الحساب<select data-account="${i}">${accounts.map(a=>`<option value="${escape(a.id)}" ${a.id===x.account_id?'selected':''}>${escape(a.name)} — المتاح ${money(a.balance,2)}</option>`).join('')}</select></label><label>المبلغ<input data-payamount="${i}" type="number" min="0.01" step="0.01" value="${x.amount}"></label><button type="button" data-removepay="${i}" class="danger">حذف الدفعة</button></div>`).join('')||'<p class="muted">لم تُضف دفعات بعد؛ الباقي يصبح دينًا بعد التأكيد.</p>';f.querySelector('[data-total]').textContent=money(purchaseTotal(items));const paid=payments.reduce((n,x)=>n+Number(x.amount||0),0);f.querySelector('[data-debt]').textContent=money(Math.max(0,purchaseTotal(items)-paid));
  f.querySelectorAll('[data-product]').forEach(x=>x.onchange=()=>items[+x.dataset.product].product_id=x.value);f.querySelectorAll('[data-qty]').forEach(x=>x.oninput=()=>{items[+x.dataset.qty].quantity=Number(x.value);draw();});f.querySelectorAll('[data-cost]').forEach(x=>x.oninput=()=>{items[+x.dataset.cost].cost=Number(x.value);draw();});f.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{items.splice(+x.dataset.remove,1);draw();});f.querySelectorAll('[data-account]').forEach(x=>x.onchange=()=>payments[+x.dataset.account].account_id=x.value);f.querySelectorAll('[data-payamount]').forEach(x=>x.oninput=()=>{payments[+x.dataset.payamount].amount=Number(x.value);draw();});f.querySelectorAll('[data-removepay]').forEach(x=>x.onclick=()=>{payments.splice(+x.dataset.removepay,1);draw();});};
 f.querySelector('[data-add]').onclick=()=>{if(!products.length)return;items.push({product_id:products[0].id,quantity:1,cost:Number(products[0].weighted_unit_cost||0)});draw();};f.querySelector('[data-pay]').onclick=()=>{if(!accounts.length)return;payments.push({account_id:accounts[0].id,amount:0});draw();};draw();
 f.onsubmit=async e=>{e.preventDefault();if(busy)return;try{const payload=purchasePayload(projectId,f.elements.supplier.value,items,payments,f.elements.note.value);const total=purchaseTotal(items),paid=payments.reduce((n,x)=>n+Number(x.amount),0);if(paid>total)throw new Error('إجمالي الدفعات أكبر من قيمة الفاتورة');if(payments.some(x=>Number(x.amount)>Number(accounts.find(a=>a.id===x.account_id)?.balance||0)))throw new Error('إحدى الدفعات أكبر من الرصيد المتاح');if(!storage)throw new Error('تخزين الجلسة مطلوب لحماية إعادة المحاولة');if(!op){const next=createOperation('confirm_sharikx2_purchase_v3',payload);storage.setItem(key,JSON.stringify({payload,requestId:next.requestId}));op=next;}busy=true;fs.disabled=true;submit.disabled=true;d.querySelector('[data-close]').disabled=true;submit.textContent='جارٍ اعتماد الفاتورة…';await op.run(api);storage.removeItem(key);d.remove();onSaved();}catch(e){err.textContent=e.message;if(e.status>=400&&e.status<500){storage?.removeItem(key);op=null;fs.disabled=false;}else if(op)err.textContent+=' — أعد المحاولة بنفس الطلب بأمان';}finally{busy=false;submit.disabled=false;d.querySelector('[data-close]').disabled=false;submit.textContent=op?'التحقق وإعادة المحاولة':'تأكيد الفاتورة';}};
 }catch(e){if(d.isConnected)d.querySelector('.body').textContent=e.message;}
}
