import {escape,money} from './ui.js';import {createOperation} from './operations.js';
export function transferPayload(projectId,from,to,amount,accounts){
 const source=accounts.find(a=>a.id===from);if(!source||!accounts.some(a=>a.id===to)||from===to)throw new Error('اختر حسابين مختلفين');
 if(!Number.isFinite(amount)||amount<=0||Math.abs(amount*100-Math.round(amount*100))>1e-7)throw new Error('أدخل مبلغًا صحيحًا حتى منزلتين عشريتين');
 if(amount>Number(source.balance))throw new Error('المبلغ أكبر من الرصيد المتاح');
 return {p_project_id:projectId,p_from_account_id:from,p_to_account_id:to,p_amount:amount,p_note:null};
}
export async function openTransfer({api,projectId,mode,storage,onSaved}){
 if(mode!=='owner')throw new Error('المشاركة للمشاهدة فقط');if(document.querySelector('.transfer-dialog'))return;
 const dialog=document.createElement('dialog');dialog.className='transfer-dialog';dialog.innerHTML='<h2>التحويل بين الحسابات</h2><div class="body"><div class="skeleton"></div></div><button data-close class="outline">إلغاء</button>';document.body.append(dialog);dialog.showModal();let busy=false,operation=null;const key=`sharikx2-pending-transfer:${projectId}`;dialog.querySelector('[data-close]').onclick=()=>{if(!busy)dialog.remove();};dialog.oncancel=e=>{if(busy)e.preventDefault();};
 try{const s=await api.summary(projectId);if(!dialog.isConnected)return;const accounts=s.accounts||[];dialog.querySelector('.body').innerHTML=`<form><fieldset><legend>من حساب</legend><div class="account-choices">${accounts.map(a=>`<label class="choice"><input type="radio" name="from" value="${escape(a.id)}" required><span>${escape(a.name)} — المتاح ${money(a.balance,2)}</span></label>`).join('')}</div><legend>إلى حساب</legend><div class="account-choices">${accounts.map(a=>`<label class="choice"><input type="radio" name="to" value="${escape(a.id)}" required><span>${escape(a.name)}</span></label>`).join('')}</div><label>مبلغ التحويل<div class="money-input"><input name="amount" type="number" step="0.01" min="0.01" inputmode="decimal" required><span>₪</span></div></label><p data-left class="muted"></p></fieldset><p role="alert"></p><button class="primary" type="submit">حفظ التحويل</button></form>`;const form=dialog.querySelector('form'),fields=form.querySelector('fieldset'),button=form.querySelector('[type=submit]'),error=form.querySelector('[role=alert]');form.oninput=()=>{const a=accounts.find(x=>x.id===form.elements.from.value);form.querySelector('[data-left]').textContent=a?`المتبقي في ${a.name}: ${money(Number(a.balance)-Number(form.elements.amount.value||0),2)}`:'';};
 try{const saved=JSON.parse(storage?.getItem(key)||'null');if(saved?.payload?.p_project_id===projectId){operation=createOperation('transfer_sharikx2_account_web_v1',saved.payload,saved.requestId);form.elements.from.value=saved.payload.p_from_account_id;form.elements.to.value=saved.payload.p_to_account_id;form.elements.amount.value=saved.payload.p_amount;fields.disabled=true;button.textContent='التحقق من التحويل السابق';}}catch{button.disabled=true;error.textContent='تعذر قراءة التحويل السابق؛ تحقق من الأرصدة قبل محاولة أخرى';}
 form.onsubmit=async e=>{e.preventDefault();if(busy)return;try{if(!operation){const payload=transferPayload(projectId,form.elements.from.value,form.elements.to.value,Number(form.elements.amount.value),accounts);if(!storage)throw new Error('تخزين الجلسة مطلوب لحماية إعادة المحاولة');const next=createOperation('transfer_sharikx2_account_web_v1',payload);storage.setItem(key,JSON.stringify({payload,requestId:next.requestId}));operation=next;}busy=true;fields.disabled=true;button.disabled=true;dialog.querySelector('[data-close]').disabled=true;button.textContent='جارٍ التحويل…';await operation.run(api);storage.removeItem(key);dialog.remove();onSaved();}catch(e){error.textContent=e.message;if(e.status>=400&&e.status<500){storage.removeItem(key);operation=null;fields.disabled=false;}else if(operation)error.textContent+=' — أعد التحقق بنفس الطلب دون تكرار التحويل';}finally{busy=false;button.disabled=false;dialog.querySelector('[data-close]').disabled=false;button.textContent=operation?'التحقق وإعادة المحاولة':'حفظ التحويل';}};
 }catch(e){if(dialog.isConnected)dialog.querySelector('.body').textContent=e.message;}
}
