import test from 'node:test';import assert from 'node:assert/strict';import {saleDraftKey,validateSaleDraft,readSaleDrafts,saveSaleDraft,removeSaleDraft,restoreSaleDraft} from '../sale-drafts.js';
const draft={version:1,id:'12345678-1234-1234-1234-123456789012',projectId:'project',cart:[{id:'p',name:'صنف',quantity:.5,stock:2,price:3.3333,cost:2,unit:'كغم',quantityStep:.5}],asDebt:false,customer:null,accountId:null};
function store(){const values=new Map();return {values,getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value)};}
test('drafts have separate project-scoped keys from immutable operations',()=>{assert.equal(saleDraftKey('project'),'sharikx2-unsent-sales-v1:project');assert.notEqual(saleDraftKey('other'),saleDraftKey('project'));});
test('draft validation copies fractional quantities/prices/payment choices without requiring payment',()=>{const copy=structuredClone(draft),value=validateSaleDraft(draft,'project');assert.deepEqual(value,copy);value.cart[0].quantity=1;assert.deepEqual(draft,copy);});
test('saving same draft updates its original position without duplicating or mutating input',()=>{const storage=store(),second={...draft,id:'22345678-1234-1234-1234-123456789012'};saveSaleDraft(storage,'project',draft);saveSaleDraft(storage,'project',second);saveSaleDraft(storage,'project',{...draft,cart:[{...draft.cart[0],price:4}]});const rows=readSaleDrafts(storage,'project');assert.equal(rows.length,2);assert.equal(rows[0].cart[0].price,4);assert.equal(rows[1].id,second.id);assert.equal(draft.cart[0].price,3.3333);});
test('removal only changes selected draft in selected project',()=>{const storage=store();saveSaleDraft(storage,'project',draft);saveSaleDraft(storage,'other',{...draft,projectId:'other'});removeSaleDraft(storage,'project',draft.id);assert.equal(readSaleDrafts(storage,'project').length,0);assert.equal(readSaleDrafts(storage,'other').length,1);});
test('corrupt lists block replacement and duplicates are rejected',()=>{const storage=store();for(const raw of ['{bad','false',JSON.stringify([draft,draft])]){storage.setItem(saleDraftKey('project'),raw);assert.throws(()=>saveSaleDraft(storage,'project',draft));assert.equal(storage.getItem(saleDraftKey('project')),raw);}});
test('invalid draft fields and unsupported storage fail explicitly',()=>{for(const mutate of [d=>d.projectId='other',d=>d.id='bad',d=>d.cart=[],d=>d.cart[0].price=-1,d=>d.cart[0].quantity=0,d=>d.cart[0].stock=NaN,d=>d.customer={id:'c'},d=>d.cart.push({...d.cart[0]})]){const value=structuredClone(draft);mutate(value);assert.throws(()=>validateSaleDraft(value,'project'));}assert.throws(()=>readSaleDrafts(null,'project'));assert.throws(()=>saveSaleDraft({getItem:()=>null,setItem(){throw Error('quota');}},'project',draft),/quota/);});
test('restoration refreshes stock/cost but preserves price and measured step',()=>{const result=restoreSaleDraft(draft,'project',{get:()=>({quantity_pieces:4,weighted_unit_cost:3})});assert.equal(result.cart[0].stock,4);assert.equal(result.cart[0].cost,3);assert.equal(result.cart[0].price,3.3333);assert.equal(result.cart[0].quantityStep,.5);assert.deepEqual(result.unavailable,[]);assert.equal(draft.cart[0].stock,2);});
test('missing or insufficient products remain visible but block quantities instead of silently dropping',()=>{for(const product of [null,{quantity_pieces:.25,weighted_unit_cost:2}]){const result=restoreSaleDraft(draft,'project',{get:()=>product});assert.deepEqual(result.unavailable,['صنف']);assert.equal(result.cart.length,1);assert.equal(result.cart[0].quantity,.5);assert.ok(result.cart[0].stock<.5);}});
